// AUTO-GENERATED by scripts/sync-pairings-data.ts
// Do not edit manually. Edit registry/pairings/*.json and re-run the script.

import type { PairingData } from "./pairings";

export const PAIRINGS_DATA: PairingData[] = [
  {
    name: "agency",
    heading: "Schibsted Grotesk",
    headingCategory: "sans-serif",
    body: "Karla",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["minimal","nordic"],
    useCase: ["agency","design","portfolio"],
    description: "Nordic minimalism meets grotesque warmth. Schibsted Grotesk's Scandinavian clarity in headlines paired with Karla's quirky grotesque personality for body text that feels human.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:wght@400;500;600;700&family=Karla:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "architect",
    heading: "Outfit",
    headingCategory: "sans-serif",
    body: "Libre Baskerville",
    bodyCategory: "serif",
    mono: "IBM Plex Mono",
    mood: ["structured","professional"],
    useCase: ["portfolio","agency","architecture"],
    description: "Structured meets refined. Outfit's geometric precision in headings contrasts beautifully with Libre Baskerville's warm readability, like blueprints meeting handwritten notes.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=Libre+Baskerville:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap",
  },
  {
    name: "beacon",
    heading: "Exo 2",
    headingCategory: "sans-serif",
    body: "Titillium Web",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["futuristic","technical"],
    useCase: ["tech","space","gaming"],
    description: "Space-age geometry. Exo 2's futuristic proportions make headlines feel like mission control, while Titillium Web's Italian polytechnic origins keep body text grounded in engineering precision.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;500;600;700&family=Titillium+Web:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "broadsheet",
    heading: "PT Serif",
    headingCategory: "serif",
    body: "PT Sans",
    bodyCategory: "sans-serif",
    mono: "Inconsolata",
    mood: ["authoritative","universal"],
    useCase: ["news","publishing","i18n"],
    description: "Russia's gift to web typography. ParaType's public text fonts — commissioned for pan-Russian readability — pair beautifully: serif headlines carry authority, sans body text ensures clarity across Cyrillic and Latin.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=PT+Serif:wght@400;500;600;700&family=PT+Sans:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "brutalist",
    heading: "Archivo Black",
    headingCategory: "sans-serif",
    body: "Archivo",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["raw","brutalist"],
    useCase: ["portfolio","art","experimental"],
    description: "Raw typographic power. Archivo Black's heavy weight fills every pixel of the headline, while regular Archivo maintains the same DNA in a readable body weight. No decoration, pure function.",
    scale: {
          "h1": {
                "size": "2.75rem",
                "weight": 800,
                "lineHeight": "1.05",
                "letterSpacing": "-0.035em"
          },
          "h2": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.75rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Archivo+Black:wght@400;500;600;700&family=Archivo:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "capsule",
    heading: "Montserrat",
    headingCategory: "sans-serif",
    body: "Karla",
    bodyCategory: "sans-serif",
    mono: "JetBrains Mono",
    mood: ["modern","bold"],
    useCase: ["fashion","retail","branding"],
    description: "Buenos Aires modernism. Montserrat channels the urban signage of its namesake neighborhood — bold, geometric, unmistakable. Karla's grotesque quirks keep body text from feeling clinical.",
    scale: {
          "h1": {
                "size": "2.75rem",
                "weight": 800,
                "lineHeight": "1.05",
                "letterSpacing": "-0.035em"
          },
          "h2": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.75rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Karla:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  {
    name: "classic",
    heading: "DM Serif Display",
    headingCategory: "serif",
    body: "Libre Baskerville",
    bodyCategory: "serif",
    mono: "JetBrains Mono",
    mood: ["literary","warm","traditional"],
    useCase: ["blog","publishing","book"],
    description: "Literary and warm serif pairing. Elegant display headings with classic body text for publishing.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 400,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "2rem",
                "weight": 400,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 400,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.7",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=DM+Serif+Display:wght@400;500;600;700&family=Libre+Baskerville:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  {
    name: "commons",
    heading: "Cabin",
    headingCategory: "sans-serif",
    body: "Mukta",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["approachable","inclusive"],
    useCase: ["community","nonprofit","education"],
    description: "Humanist warmth across scripts. Cabin's slightly condensed forms give headings a distinct character, while Mukta — designed for both Devanagari and Latin — brings inclusive readability to body text.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "1.75rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.375rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.005em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&family=Mukta:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "corporate",
    heading: "Roboto",
    headingCategory: "sans-serif",
    body: "Roboto",
    bodyCategory: "sans-serif",
    mono: "Roboto Mono",
    mood: ["neutral","systematic"],
    useCase: ["enterprise","Android","Material Design"],
    description: "Google's type system. Roboto's dual nature — mechanical skeleton with friendly curves — creates a cohesive experience from headlines to fine print. The de facto standard for Material Design.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600;700&family=Roboto+Mono:wght@400;500&display=swap",
  },
  {
    name: "creative",
    heading: "Space Grotesk",
    headingCategory: "sans-serif",
    body: "DM Sans",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["playful","startup","geometric"],
    useCase: ["landing page","startup","portfolio"],
    description: "Playful geometric pairing. Bold headings with friendly body text for startups and portfolios.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=DM+Sans:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "curator",
    heading: "Plus Jakarta Sans",
    headingCategory: "sans-serif",
    body: "PT Serif",
    bodyCategory: "serif",
    mono: "Source Code Pro",
    mood: ["curated","contemporary"],
    useCase: ["gallery","museum","portfolio"],
    description: "Contemporary curation. Plus Jakarta Sans brings Indonesian design heritage to bold headings, while PT Serif delivers ParaType's exceptional Cyrillic and Latin body text.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "1.75rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.375rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.005em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=PT+Serif:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "dashboard",
    heading: "Manrope",
    headingCategory: "sans-serif",
    body: "DM Sans",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["analytical","clear"],
    useCase: ["dashboard","analytics","admin"],
    description: "Data-driven clarity. Manrope's optical corrections make dense dashboards legible, while DM Sans handles labels and descriptions with compact efficiency.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&family=DM+Sans:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "devtool",
    heading: "Red Hat Display",
    headingCategory: "sans-serif",
    body: "Red Hat Display",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["technical","open-source"],
    useCase: ["developer tools","documentation","open source"],
    description: "Open-source identity. Red Hat Display balances geometric precision with humanist warmth, creating a type system that feels both technical and approachable — exactly what developer tools need.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;500;600;700&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "digest",
    heading: "Bitter",
    headingCategory: "serif",
    body: "Open Sans",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["reliable","editorial"],
    useCase: ["newsletter","blog","content"],
    description: "Slab-serif substance. Bitter's sturdy slab serifs were designed specifically for screen reading, making headlines feel anchored and authoritative. Open Sans handles the body with effortless neutrality.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&family=Open+Sans:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "dispatch",
    heading: "Heebo",
    headingCategory: "sans-serif",
    body: "Assistant",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["neutral","inclusive"],
    useCase: ["i18n","enterprise","communication"],
    description: "Hebrew-Latin harmony. Heebo's geometric forms designed for both scripts create inclusive headlines, while Assistant — with similar dual-script DNA — maintains that consistency through body text.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&family=Assistant:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "document",
    heading: "Source Sans 3",
    headingCategory: "sans-serif",
    body: "Source Sans 3",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["professional","versatile"],
    useCase: ["documentation","enterprise","publishing"],
    description: "Adobe's open-source superfamily. Source Sans 3's humanist proportions excel in UI and documents alike, with Source Code Pro maintaining the same vertical metrics for seamless mixed content.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "1.75rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.375rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.005em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;500;600;700&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "dossier",
    heading: "Barlow Condensed",
    headingCategory: "sans-serif",
    body: "Barlow",
    bodyCategory: "sans-serif",
    mono: "IBM Plex Mono",
    mood: ["efficient","modern"],
    useCase: ["dashboard","data","news"],
    description: "California grotesk in two widths. Barlow Condensed packs maximum information into headlines, while regular Barlow breathes in body text. A superfamily designed for screen-first interfaces.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;500;600;700&family=Barlow:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap",
  },
  {
    name: "editorial",
    heading: "Playfair Display",
    headingCategory: "serif",
    body: "Source Serif 4",
    bodyCategory: "serif",
    mono: "JetBrains Mono",
    mood: ["elegant","traditional","authoritative"],
    useCase: ["blog","editorial","magazine","documentation"],
    description: "Classic editorial pairing. High-contrast serif headings with readable serif body text.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=Source+Serif+4:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  {
    name: "fintech",
    heading: "Outfit",
    headingCategory: "sans-serif",
    body: "IBM Plex Sans",
    bodyCategory: "sans-serif",
    mono: "IBM Plex Mono",
    mood: ["trustworthy","precise"],
    useCase: ["fintech","banking","enterprise"],
    description: "Trust through typography. Outfit's geometric clarity inspires confidence in headings, while IBM Plex's rigorous design system ensures readability in data-heavy financial interfaces.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap",
  },
  {
    name: "folio",
    heading: "Josefin Sans",
    headingCategory: "sans-serif",
    body: "Raleway",
    bodyCategory: "sans-serif",
    mono: "Roboto Mono",
    mood: ["elegant","sophisticated"],
    useCase: ["portfolio","fashion","luxury"],
    description: "Vintage geometry meets modern elegance. Josefin Sans's 1920s-inspired letterforms create distinctive headlines, while Raleway's refined thin weights bring fashion-forward sophistication to body text.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;500;600;700&family=Raleway:wght@400;500;600&family=Roboto+Mono:wght@400;500&display=swap",
  },
  {
    name: "gazette",
    heading: "Cormorant Garamond",
    headingCategory: "serif",
    body: "Raleway",
    bodyCategory: "sans-serif",
    mono: "Roboto Mono",
    mood: ["elegant","dramatic"],
    useCase: ["magazine","luxury","fashion"],
    description: "Old-world elegance meets contemporary grace. Cormorant Garamond's delicate high-contrast strokes create dramatic headlines, balanced by Raleway's geometric sophistication.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 400,
                "lineHeight": "1.15",
                "letterSpacing": "-0.015em"
          },
          "h2": {
                "size": "2rem",
                "weight": 400,
                "lineHeight": "1.2",
                "letterSpacing": "-0.01em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 400,
                "lineHeight": "1.3",
                "letterSpacing": "0em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "0em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.75",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Raleway:wght@400;500;600&family=Roboto+Mono:wght@400;500&display=swap",
  },
  {
    name: "govtech",
    heading: "Public Sans",
    headingCategory: "sans-serif",
    body: "Lato",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["trustworthy","accessible"],
    useCase: ["government","healthcare","public sector"],
    description: "Government-grade clarity. Public Sans was designed for the US Web Design System — strong, neutral, and accessible. Paired with Lato's warm humanist body text for approachable civic interfaces.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "1.75rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.375rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.005em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Public+Sans:wght@400;500;600;700&family=Lato:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "handbook",
    heading: "Lexend",
    headingCategory: "sans-serif",
    body: "Lexend",
    bodyCategory: "sans-serif",
    mono: "Inconsolata",
    mood: ["accessible","clear"],
    useCase: ["education","documentation","accessibility"],
    description: "Designed for readability research. Lexend's variable font axes were fine-tuned through scientific studies to reduce visual noise and increase reading proficiency.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "1.75rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.375rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.005em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Lexend:wght@400;500;600;700&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "headline",
    heading: "Anton",
    headingCategory: "sans-serif",
    body: "Work Sans",
    bodyCategory: "sans-serif",
    mono: "Roboto Mono",
    mood: ["bold","impactful"],
    useCase: ["news","sports","media"],
    description: "Bold and unapologetic. Anton's narrow, impactful letterforms dominate the viewport, while Work Sans's humanist warmth grounds the reading experience in comfortable body text.",
    scale: {
          "h1": {
                "size": "2.75rem",
                "weight": 800,
                "lineHeight": "1.05",
                "letterSpacing": "-0.035em"
          },
          "h2": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.75rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Anton:wght@400;500;600;700&family=Work+Sans:wght@400;500;600&family=Roboto+Mono:wght@400;500&display=swap",
  },
  {
    name: "health",
    heading: "Figtree",
    headingCategory: "sans-serif",
    body: "Overpass",
    bodyCategory: "sans-serif",
    mono: "Inconsolata",
    mood: ["calm","clear"],
    useCase: ["healthcare","wellness","medical"],
    description: "Calm and clear. Figtree's friendly geometry in headings paired with Overpass's Highway Gothic roots — designed to be read at speed. Perfect for interfaces where clarity saves lives.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "1.75rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.375rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.005em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700&family=Overpass:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "impact",
    heading: "Fjalla One",
    headingCategory: "sans-serif",
    body: "Josefin Sans",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["impactful","commanding"],
    useCase: ["media","sports","marketing"],
    description: "Condensed power meets art deco elegance. Fjalla One's Nordic condensed forms dominate the headline, while Josefin Sans's vintage geometric proportions add character to every paragraph.",
    scale: {
          "h1": {
                "size": "2.75rem",
                "weight": 800,
                "lineHeight": "1.05",
                "letterSpacing": "-0.035em"
          },
          "h2": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.75rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Fjalla+One:wght@400;500;600;700&family=Josefin+Sans:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "journal",
    heading: "Merriweather",
    headingCategory: "serif",
    body: "Mulish",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["reliable","readable"],
    useCase: ["blog","journal","publishing"],
    description: "Purpose-built for reading. Merriweather's sturdy serifs hold up at any size, paired with Mulish's neutral warmth for body text that keeps readers engaged paragraph after paragraph.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Merriweather:wght@400;500;600;700&family=Mulish:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "launch",
    heading: "Sora",
    headingCategory: "sans-serif",
    body: "Public Sans",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["modern","confident"],
    useCase: ["startup","landing page","product"],
    description: "Launch-ready confidence. Sora's geometric precision with optical adjustments makes bold headlines pop, while Public Sans — born from US government accessibility standards — ensures every word lands clearly.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700&family=Public+Sans:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "literary",
    heading: "EB Garamond",
    headingCategory: "serif",
    body: "Crimson Text",
    bodyCategory: "serif",
    mono: "Inconsolata",
    mood: ["scholarly","literary"],
    useCase: ["publishing","literature","academic"],
    description: "Pure literary elegance. Two old-style serifs in conversation — Garamond's refined Renaissance forms meet Crimson's contemporary interpretation, creating a scholarly harmony.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 400,
                "lineHeight": "1.15",
                "letterSpacing": "-0.015em"
          },
          "h2": {
                "size": "2rem",
                "weight": 400,
                "lineHeight": "1.2",
                "letterSpacing": "-0.01em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 400,
                "lineHeight": "1.3",
                "letterSpacing": "0em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "0em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.75",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600;700&family=Crimson+Text:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "manifesto",
    heading: "Roboto Slab",
    headingCategory: "serif",
    body: "Roboto",
    bodyCategory: "sans-serif",
    mono: "Roboto Mono",
    mood: ["systematic","professional"],
    useCase: ["enterprise","Material Design","documentation"],
    description: "The complete Roboto system. Slab headlines bring gravitas to Google's most versatile typeface family. A three-weight system that works everywhere, from Android to enterprise dashboards.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;500;600;700&family=Roboto:wght@400;500;600&family=Roboto+Mono:wght@400;500&display=swap",
  },
  {
    name: "memoir",
    heading: "Bitter",
    headingCategory: "serif",
    body: "Lora",
    bodyCategory: "serif",
    mono: "Inconsolata",
    mood: ["warm","narrative"],
    useCase: ["blog","memoir","longform"],
    description: "Two screen-first serifs in harmony. Bitter's sturdy slab headlines ground the page, while Lora's calligraphic curves make every paragraph feel like turning a page in a favorite book.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 400,
                "lineHeight": "1.15",
                "letterSpacing": "-0.015em"
          },
          "h2": {
                "size": "2rem",
                "weight": 400,
                "lineHeight": "1.2",
                "letterSpacing": "-0.01em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 400,
                "lineHeight": "1.3",
                "letterSpacing": "0em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "0em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.75",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&family=Lora:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "minimal",
    heading: "Geist",
    headingCategory: "sans-serif",
    body: "Geist",
    bodyCategory: "sans-serif",
    mono: "Geist Mono",
    mood: ["modern","minimal","Vercel-style"],
    useCase: ["SaaS","developer tools","Vercel-style"],
    description: "Ultra-minimal Vercel-style pairing. One font family for everything, clean and modern.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "",
  },
  {
    name: "modern-clean",
    heading: "Inter",
    headingCategory: "sans-serif",
    body: "Inter",
    bodyCategory: "sans-serif",
    mono: "Geist Mono",
    mood: ["clean","neutral","SaaS"],
    useCase: ["SaaS","dashboard","web app"],
    description: "Clean and neutral sans-serif pairing. Perfect for SaaS dashboards and web applications.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap",
  },
  {
    name: "newspaper",
    heading: "Playfair Display",
    headingCategory: "serif",
    body: "DM Sans",
    bodyCategory: "sans-serif",
    mono: "JetBrains Mono",
    mood: ["sophisticated","editorial"],
    useCase: ["news","magazine","blog"],
    description: "High-contrast editorial with a modern twist. Playfair's sharp serifs cut through DM Sans's soft geometry, creating a sophisticated tension between tradition and modernity.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=DM+Sans:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  {
    name: "novel",
    heading: "Cormorant Garamond",
    headingCategory: "serif",
    body: "Lora",
    bodyCategory: "serif",
    mono: "JetBrains Mono",
    mood: ["dramatic","literary"],
    useCase: ["publishing","book","longform"],
    description: "For stories worth telling. Cormorant's dramatic display weight arrests attention at the chapter level, while Lora's brush-inspired curves make each paragraph a pleasure to read.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 400,
                "lineHeight": "1.15",
                "letterSpacing": "-0.015em"
          },
          "h2": {
                "size": "2rem",
                "weight": 400,
                "lineHeight": "1.2",
                "letterSpacing": "-0.01em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 400,
                "lineHeight": "1.3",
                "letterSpacing": "0em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "0em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.75",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Lora:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  {
    name: "playful",
    heading: "Quicksand",
    headingCategory: "sans-serif",
    body: "Cabin",
    bodyCategory: "sans-serif",
    mono: "Inconsolata",
    mood: ["playful","approachable"],
    useCase: ["kids","education","consumer app"],
    description: "Rounded and inviting. Quicksand's perfectly circular counters give headings a toy-like friendliness, while Cabin's humanist proportions keep body text grounded and professional.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "1.75rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.375rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.005em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&family=Cabin:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "poster",
    heading: "Oswald",
    headingCategory: "sans-serif",
    body: "Barlow",
    bodyCategory: "sans-serif",
    mono: "Inconsolata",
    mood: ["commanding","editorial"],
    useCase: ["media","news","marketing"],
    description: "Condensed impact. Oswald's tall proportions make every headline a statement, balanced by Barlow's slightly rounded sans-serif that adds approachability to the mechanical strength.",
    scale: {
          "h1": {
                "size": "2.75rem",
                "weight": 800,
                "lineHeight": "1.05",
                "letterSpacing": "-0.035em"
          },
          "h2": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.75rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Barlow:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "product",
    heading: "Plus Jakarta Sans",
    headingCategory: "sans-serif",
    body: "Inter",
    bodyCategory: "sans-serif",
    mono: "JetBrains Mono",
    mood: ["friendly","professional"],
    useCase: ["SaaS","product","web app"],
    description: "Product-focused clarity. Jakarta's slightly warmer geometry gives headings personality without the noise, while Inter handles the fine print with surgical precision.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  {
    name: "protocol",
    heading: "Saira",
    headingCategory: "sans-serif",
    body: "Ubuntu",
    bodyCategory: "sans-serif",
    mono: "IBM Plex Mono",
    mood: ["technical","distinctive"],
    useCase: ["developer tools","Linux","open source"],
    description: "Racing DNA meets open-source philosophy. Saira's motorsport-inspired geometry powers through headlines, while Ubuntu's distinctive humanist forms — Canonical's signature typeface — make body text unmistakably modern.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Saira:wght@400;500;600;700&family=Ubuntu:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap",
  },
  {
    name: "saas",
    heading: "Urbanist",
    headingCategory: "sans-serif",
    body: "Libre Franklin",
    bodyCategory: "sans-serif",
    mono: "JetBrains Mono",
    mood: ["clean","startup"],
    useCase: ["SaaS","pricing page","product"],
    description: "SaaS-native typography. Urbanist's low-contrast geometric forms feel at home in navigation and pricing, while Libre Franklin's newsprint heritage makes feature descriptions feel trustworthy.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Urbanist:wght@400;500;600;700&family=Libre+Franklin:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
  },
  {
    name: "scholar",
    heading: "EB Garamond",
    headingCategory: "serif",
    body: "Inter",
    bodyCategory: "sans-serif",
    mono: "Source Code Pro",
    mood: ["academic","refined"],
    useCase: ["documentation","research","education"],
    description: "Academic precision meets digital clarity. EB Garamond's renaissance roots lend authority to headings, while Inter ensures perfect screen readability for long-form content.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 400,
                "lineHeight": "1.15",
                "letterSpacing": "-0.015em"
          },
          "h2": {
                "size": "2rem",
                "weight": 400,
                "lineHeight": "1.2",
                "letterSpacing": "-0.01em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 400,
                "lineHeight": "1.3",
                "letterSpacing": "0em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "0em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.75",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600;700&family=Inter:wght@400;500;600&family=Source+Code+Pro:wght@400;500&display=swap",
  },
  {
    name: "social",
    heading: "Poppins",
    headingCategory: "sans-serif",
    body: "Hind",
    bodyCategory: "sans-serif",
    mono: "Roboto Mono",
    mood: ["friendly","warm"],
    useCase: ["social media","consumer app","i18n"],
    description: "Global-ready friendliness. Poppins brings Indian Type Foundry's geometric warmth to headlines, while Hind's Devanagari-first design ensures beautiful rendering across Latin and Indic scripts.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&family=Hind:wght@400;500;600&family=Roboto+Mono:wght@400;500&display=swap",
  },
  {
    name: "startup",
    heading: "Nunito",
    headingCategory: "sans-serif",
    body: "Nunito Sans",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["friendly","approachable"],
    useCase: ["startup","consumer app","landing page"],
    description: "Friendly and approachable. Nunito's rounded terminals give headings warmth, while Nunito Sans straightens out for professional body text. The family that grows with your product.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&family=Nunito+Sans:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "storyteller",
    heading: "Lora",
    headingCategory: "serif",
    body: "Nunito Sans",
    bodyCategory: "sans-serif",
    mono: "Inconsolata",
    mood: ["warm","narrative"],
    useCase: ["blog","storytelling","content"],
    description: "Warm and inviting. Lora's brushed curves bring narrative warmth to headlines, while Nunito Sans's rounded terminals keep body text approachable and easy to scan.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Nunito+Sans:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "studio",
    heading: "Bricolage Grotesque",
    headingCategory: "sans-serif",
    body: "Figtree",
    bodyCategory: "sans-serif",
    mono: "Fira Code",
    mood: ["creative","distinctive"],
    useCase: ["design studio","agency","creative"],
    description: "Design-forward pairing. Bricolage Grotesque's distinctive ink traps and angular terminals command attention, softened by Figtree's friendly geometric body text.",
    scale: {
          "h1": {
                "size": "2.75rem",
                "weight": 800,
                "lineHeight": "1.05",
                "letterSpacing": "-0.035em"
          },
          "h2": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.75rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;500;600;700&family=Figtree:wght@400;500;600&family=Fira+Code:wght@400;500&display=swap",
  },
  {
    name: "swiss",
    heading: "Inter Tight",
    headingCategory: "sans-serif",
    body: "Open Sans",
    bodyCategory: "sans-serif",
    mono: "IBM Plex Mono",
    mood: ["neutral","systematic"],
    useCase: ["enterprise","dashboard","admin"],
    description: "Neo-grotesque precision. Inter Tight's condensed proportions pack more information into headlines without sacrificing legibility, while Open Sans provides the reliable body text that 40% of the web already trusts.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.15",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700&family=Open+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap",
  },
  {
    name: "technical",
    heading: "IBM Plex Sans",
    headingCategory: "sans-serif",
    body: "IBM Plex Sans",
    bodyCategory: "sans-serif",
    mono: "IBM Plex Mono",
    mood: ["professional","corporate","IBM-style"],
    useCase: ["documentation","enterprise","developer tools"],
    description: "Professional IBM Plex family pairing. Designed for documentation and enterprise applications.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.02em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.2",
                "letterSpacing": "-0.015em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 500,
                "lineHeight": "1.3",
                "letterSpacing": "-0.01em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap",
  },
  {
    name: "thesis",
    heading: "Noto Serif",
    headingCategory: "serif",
    body: "Noto Sans",
    bodyCategory: "sans-serif",
    mono: "Inconsolata",
    mood: ["universal","professional"],
    useCase: ["documentation","i18n","enterprise"],
    description: "The universal pairing. Noto's unified design system ensures consistent rendering across every language and script. Truly global typography with no tofu.",
    scale: {
          "h1": {
                "size": "2.25rem",
                "weight": 700,
                "lineHeight": "1.2",
                "letterSpacing": "-0.025em"
          },
          "h2": {
                "size": "1.875rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.02em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.3",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.65",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Noto+Serif:wght@400;500;600;700&family=Noto+Sans:wght@400;500;600&family=Inconsolata:wght@400;500&display=swap",
  },
  {
    name: "venture",
    heading: "Jost",
    headingCategory: "sans-serif",
    body: "Rubik",
    bodyCategory: "sans-serif",
    mono: "Roboto Mono",
    mood: ["bold","geometric"],
    useCase: ["venture capital","finance","landing page"],
    description: "Futura-inspired ambition. Jost channels Paul Renner's geometric ideals for commanding headlines, softened by Rubik's slightly rounded sans-serif that adds just enough warmth for comfortable reading.",
    scale: {
          "h1": {
                "size": "2.5rem",
                "weight": 700,
                "lineHeight": "1.1",
                "letterSpacing": "-0.03em"
          },
          "h2": {
                "size": "2rem",
                "weight": 600,
                "lineHeight": "1.15",
                "letterSpacing": "-0.025em"
          },
          "h3": {
                "size": "1.5rem",
                "weight": 600,
                "lineHeight": "1.25",
                "letterSpacing": "-0.015em"
          },
          "h4": {
                "size": "1.25rem",
                "weight": 500,
                "lineHeight": "1.35",
                "letterSpacing": "-0.01em"
          },
          "h5": {
                "size": "1.125rem",
                "weight": 500,
                "lineHeight": "1.4",
                "letterSpacing": "0em"
          },
          "h6": {
                "size": "1rem",
                "weight": 500,
                "lineHeight": "1.5",
                "letterSpacing": "0em"
          },
          "body": {
                "size": "1rem",
                "lineHeight": "1.6",
                "weight": 400
          }
    },
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Jost:wght@400;500;600;700&family=Rubik:wght@400;500;600&family=Roboto+Mono:wght@400;500&display=swap",
  }
];
