/**
 * Syncs registry/fonts/*.json → lib/fonts-data.ts
 * Generates a static TypeScript file with all font data
 * that can be imported by both server and client components.
 *
 * Usage: bun run scripts/sync-fonts-data.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const FONTS_DIR = join(import.meta.dir, "..", "registry", "fonts");
const OUTPUT = join(import.meta.dir, "..", "lib", "fonts-data.ts");

function main() {
  const files = readdirSync(FONTS_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();

  const entries: string[] = [];

  for (const file of files) {
    const raw = JSON.parse(readFileSync(join(FONTS_DIR, file), "utf-8"));
    entries.push(`  ${JSON.stringify(raw)}`);
  }

  const output = `// AUTO-GENERATED by scripts/sync-fonts-data.ts
// Do not edit manually. Edit registry/fonts/*.json and re-run the script.

import type { FontItem } from "./registry";

export const FONTS_DATA: FontItem[] = [
${entries.join(",\n")}
];
`;

  writeFileSync(OUTPUT, output);
  console.log(`Generated lib/fonts-data.ts with ${entries.length} fonts`);
}

main();
